issueConfigs:
  -
    bannedTitle: "问题简单描述"
    subtitles:
      - "问题复现步骤："
      - "期望的表现："
      - "观察到的表现："
      - "屏幕截图或动态图："
    bannedContents:
      - "第一步"
      - "第二步"
      - "其他步骤..."
      - "在这里描述期望的表现"
      - "在这里描述观察到的表现"
      - "复现步骤的屏幕截图和动态 GIF 图"
      - "图片的 url",
      - "建议提供可运行的demo"
  -
    bannedTitle: "在此简单描述您的建议"
    subtitles:
      - "新功能相关的问题issue或讨论："
      - "新功能的实现："
      - "相关项目或文档："
    bannedContents:
      - "在这里引用新功能相关的讨论"
      - "在这里填写或简单描述功能的实现方式或需求的解决方式"
      - "在这里引用相关项目或文档地址"

comments:
  closeIssue: "issue不符合格式要求，请确保格式正确且填写所有有效信息。\n请保留issue模板中的各级小标题（如“期望的表现：”），并使用有效信息替换模板默认内容（如“[在这里描述期望的表现]”）"
